// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEQ8JMFpP0BZTVscpmRPNKk-gukgq8LI8',
    appId: '1:116785338913:web:2d16d35b1e46b923e7e160',
    messagingSenderId: '116785338913',
    projectId: 'dailydose-91a6d',
    authDomain: 'dailydose-91a6d.firebaseapp.com',
    storageBucket: 'dailydose-91a6d.firebasestorage.app',
    measurementId: 'G-4FVKYLNDQW',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM39NRq3CllUsPkkLY2i93m9MpRR_EfzM',
    appId: '1:116785338913:ios:116c618a6eceaa52e7e160',
    messagingSenderId: '116785338913',
    projectId: 'dailydose-91a6d',
    storageBucket: 'dailydose-91a6d.firebasestorage.app',
    iosBundleId: 'com.example.dailyDoseMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM39NRq3CllUsPkkLY2i93m9MpRR_EfzM',
    appId: '1:116785338913:ios:116c618a6eceaa52e7e160',
    messagingSenderId: '116785338913',
    projectId: 'dailydose-91a6d',
    storageBucket: 'dailydose-91a6d.firebasestorage.app',
    iosBundleId: 'com.example.dailyDoseMobile',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwlgXVBPwqQm-huJriJBIzvwo_Lx9TSwc',
    appId: '1:116785338913:android:0307dac4a5b1a1ede7e160',
    messagingSenderId: '116785338913',
    projectId: 'dailydose-91a6d',
    storageBucket: 'dailydose-91a6d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEQ8JMFpP0BZTVscpmRPNKk-gukgq8LI8',
    appId: '1:116785338913:web:92428b55b2d29dfde7e160',
    messagingSenderId: '116785338913',
    projectId: 'dailydose-91a6d',
    authDomain: 'dailydose-91a6d.firebaseapp.com',
    storageBucket: 'dailydose-91a6d.firebasestorage.app',
    measurementId: 'G-SD309GM626',
  );

}